In [20]:
import xml.etree.ElementTree as ET
import pandas as pd

tree = ET.parse("./laptops_train_sb1.xml")
root = tree.getroot()

rows = []

for sentence in root.findall(".//sentence"):
    sent_id = sentence.get("id")
    text = sentence.find("text").text
    
    opinions = sentence.find("Opinions")
    
    if opinions is not None and len(opinions) > 0:
        for op in opinions.findall("Opinion"):
            rows.append({
                "sentence_id": sent_id,
                "text": text,
                "category": op.get("category"),
                "polarity": op.get("polarity")
            })
    else:
        rows.append({
            "sentence_id": sent_id,
            "text": text,
            "category": None,
            "polarity": None
        })

df = pd.DataFrame(rows)

In [17]:
df.head()

,sentence_id,text,category,polarity
0,79:0,Being a PC user my whole life....,NaN,NaN
1,79:1,This computer is absolutely AMAZING!!!,LAPTOP#GENERAL,positive
2,79:2,10 plus hours of battery...,BATTERY#OPERATION_PERFORMANCE,positive
3,79:3,super fast processor and really nice graphics ...,CPU#OPERATION_PERFORMANCE,positive
4,79:3,super fast processor and really nice graphics ...,GRAPHICS#GENERAL,positive

In [15]:
df.shape

(3370, 4)

In [4]:
df["polarity"].value_counts()

polarity
positive    1637
negative    1084
neutral      188
Name: count, dtype: int64

In [5]:
import xml.etree.ElementTree as ET
import pandas as pd

tree = ET.parse("./restaurants_train_sb1.xml")
root = tree.getroot()

rows = []

for sentence in root.findall(".//sentence"):
    sent_id = sentence.get("id")
    text = sentence.find("text").text
    
    opinions = sentence.find("Opinions")
    
    if opinions is not None and len(opinions) > 0:
        for op in opinions.findall("Opinion"):
            rows.append({
                "sentence_id": sent_id,
                "text": text,
                "category": op.get("category"),
                "polarity": op.get("polarity")
            })
    else:
        rows.append({
            "sentence_id": sent_id,
            "text": text,
            "category": None,
            "polarity": None
        })

df = pd.DataFrame(rows)

In [6]:
df.head()

,sentence_id,text,category,polarity
0,1004293:0,Judging from previous posts this used to be a ...,RESTAURANT#GENERAL,negative
1,1004293:1,"We, there were four of us, arrived at noon - t...",SERVICE#GENERAL,negative
2,1004293:2,"They never brought us complimentary noodles, i...",SERVICE#GENERAL,negative
3,1004293:3,The food was lousy - too sweet or too salty an...,FOOD#QUALITY,negative
4,1004293:3,The food was lousy - too sweet or too salty an...,FOOD#STYLE_OPTIONS,negative

In [7]:
df.shape

(2799, 4)

In [8]:
df["polarity"].value_counts()

polarity
positive    1657
negative     749
neutral      101
Name: count, dtype: int64

In [8]:
import xml.etree.ElementTree as ET
import pandas as pd

tree = ET.parse("./laptops_test_sb1.xml")
root = tree.getroot()

rows = []

for review in root.findall(".//Review"):
    review_id = review.get("rid")
    
    for sentence in review.findall(".//sentence"):
        sent_id = sentence.get("id")
        text = sentence.find("text").text
        
        opinions = sentence.find("Opinions")
        
        # if no opinions → still keep row
        if opinions is None or len(opinions) == 0:
            rows.append({
                # "review_id": review_id,
                # "sentence_id": sent_id,
                "text": text,
                "category": None,
                "polarity": None
            })
        else:
            for op in opinions.findall("Opinion"):
                rows.append({
                    # "review_id": review_id,
                    # "sentence_id": sent_id,
                    "text": text,
                    "category": op.get("category"),
                    "polarity": op.get("polarity")
                })

df = pd.DataFrame(rows)

df.head()

,text,category,polarity
0,"Well, my first apple computer and I am impressed.",LAPTOP#GENERAL,positive
1,"Works well, fast and no reboots.",LAPTOP#OPERATION_PERFORMANCE,positive
2,Waiting to install MS Office and see how it go...,NaN,NaN
3,"Have always been a PC guy, but decided to try ...",NaN,NaN
4,Glad I did so far.,COMPANY#GENERAL,positive

In [4]:
df.shape

(1036, 5)